### ISSUE TITLE
"other" option

### ISSUE THREAD

**Issue by Remi-Gau** [INCF/artem-is#1]
Add option “other” to both the ARTEM-IS template and cobidas_artemis table + instruction to specify further in the ARTEM-IS template + new item to specify further if “other” has been selected in the cobidas_artemis table

[Source](https://docs.google.com/document/d/1RUSBZc_jRpvd2mbr_Ple8GALuwewO1uz5Fu4U0Q4krA/edit#bookmark=id.fqsg6j4z23jz)

**Comment by asoskic** [comment]
This should be added everywhere now, but it would be good to check whether the option other and/or its follow-up question are missing from somewhere. :)
