### ISSUE TITLE
add mkdocs with user and developpers doc

### ISSUE THREAD

**Issue by Remi-Gau** [INCF/artem-is#109]

**Comment by onemriganka** [comment]
Hey, and you describe more about the bug . i will  try my best to fix it

**Comment by Remi-Gau** [comment]
@onemriganka I will create a basic infrastructure so it is easier for you and anyone else to update the documentation

**Comment by onemriganka** [comment]
i want to contribute to the project , so  i will wait for that ....

**Comment by Remi-Gau** [comment]
I have set things up. 

https://incf.github.io/artem-is/

So if you want edit the documentation it should "just" be a matter of editing markdown files.

On any page of the website there is a 🖊️ icon that when clicked should open the relevant markdown file to modify.

You can (of course) use a more "local" workflow by forking and cloning the repository to work on it outside of the of the github interface: this may be actually much easier when it comes to changing several pages or adding new pages.

Probably a good idea to check with @asoskic and the rest of the team to see what is the plan for the content of the doc.

will close this issue for now: you can keep on posting in it, but maybe better to open another issue to talk about the content of the doc
