### ISSUE TITLE
use of the details column for long instructions

### ISSUE THREAD

**Issue by Remi-Gau** [INCF/artem-is#12]
Questions with complicated instructions (e.g., stuff separated by a semicolon) should be simplified either by adding help or better yet by making people fill them in in the way you cannot get it wrong by changing question type

[source](https://docs.google.com/document/d/1RUSBZc_jRpvd2mbr_Ple8GALuwewO1uz5Fu4U0Q4krA/edit#bookmark=id.810o0ki6hzrc)

**Comment by asoskic** [comment]
At the moment, this is changed everywhere where we thought it was safe to move instructions into Details column.

What can be done in the future: change the way information is filled in for these questions so that it is not easy to get it wrong (issue https://github.com/INCF/artem-is/issues/79)
