### ISSUE TITLE
Update web-app About section

### ISSUE THREAD

**Issue by asoskic** [INCF/artem-is#122]
This is the new text: https://github.com/INCF/artem-is#readme

**Comment by Amanyadav207** [comment]
Please explain this issue in detail.

**Comment by vinayakgavariya** [comment]
Hey @asoskic 

I just read about artem-is and I think it's really useful for folks. And I would like to improve the about section.

Can you please assign this issue.

**Comment by asoskic** [comment]
Thank you both for your kind offers and your interest in our project! Sadly we haven't figured out and found the time yet to make the web app backend code publicly available in a meaningful way, allowing us to involve new contributors to the web app programming side of the project. I hope this will change in the future, though!

Meanwhile, we have updated the web app description, so I am closing this issue.
