### ISSUE TITLE
What was the length/order of the high-pass filter?

### ISSUE THREAD

**Issue by Remi-Gau** [INCF/artem-is#15]
Maybe an example could be added here so that the users know which format to use when writing the length/order e.g. 60Hz

from [KatarinaKetrinStekic](https://github.com/KatarinaKetrinStekic)

source: https://github.com/Remi-Gau/artemis_checklist/issues/28

**Comment by asoskic** [comment]
This is a numerical item, so there is not much to put as an example.

**Comment by asoskic** [comment]
Ok let me think if an explanation can be added

**Comment by asoskic** [comment]
+ not to forget: remove length because length and order are not the same

**Comment by asoskic** [comment]
This is something that needs to be addressed in the lexicon, because the value is just an ordinal number, like 1st order, 2nd order...

p.s. length removed
