### ISSUE TITLE
Warning about unfilled items

### ISSUE THREAD

**Issue by Remi-Gau** [INCF/artem-is#16]
Add flagging for Required items that have not been filled in for review before saving and exiting

From [asoskic](https://github.com/asoskic)

Source: https://github.com/Remi-Gau/artemis_checklist/issues/14

**Comment by asoskic** [comment]
Better option: add a clear note that not all visible items are completed

**Comment by asoskic** [comment]
That way, people can save half-baked templates

**Comment by asoskic** [comment]
In the PDF, warning to be changed to this and to be red:
*`Answer not provided` instead of `empty`

Within application - add a mark that a question has been completed for easier search for questions that have not been filled in
