### ISSUE TITLE
Display contributors' names on output files (PDF)

### ISSUE THREAD

**Issue by ufangYang** [INCF/artem-is#41]
How about displaying the name of the person who created the template on the output file as an option? As an alternative being anonymous is also an option.

**Comment by asoskic** [comment]
I like the suggestion about adding contributors to PDF, and I don't think anonymous should be an option. I am not sure about JSON files though, because you could download and upload these files to different accounts who can then make further changes.

**Comment by asoskic** [comment]
This is already there on both PDF and JSON outputs :)
