### ISSUE TITLE
Notch filters - which information should be included

### ISSUE THREAD

**Issue by Remi-Gau** [INCF/artem-is#5]
Include notch filters into pre-processing? What options are needed? Also - what do we include for high-pass and low-pass filters? Ask Robert Oostenveld and Giorgio

[source](https://docs.google.com/document/d/1RUSBZc_jRpvd2mbr_Ple8GALuwewO1uz5Fu4U0Q4krA/edit#bookmark=id.izueyooiad6n)

**Comment by asoskic** [comment]
From Robert:

“Notch” or time-domain filters to remove the power line noise can be implemented in different ways; I am aware of two or three “methods” (with considerable methodological overlap),  each with its own parametrization: as a FIR or IIR bandstop filter with 3dB points and rolloff (see https://www.electronics-tutorials.ws/filter/band-stop-filter.html) or specified as a notch filter with a Q-factor,  and as a DFT (discrete Fourier transform) aka Sinc https://en.wikipedia.org/wiki/Sinc_filter filter with a spectral resolution and specification of the band or bands that are removed. I doubt that many neuroscientists know the details and would be able to specify this correctly, although it would be good if software (including fieldtrip) would specify this better.
I think that center frequency (50 or 60) and “width” (that would correspond to the distance between 3db points, or the number of removed frequencies in a DFT)) are decent specifications. It should also specify whether - and if so which - harmonics are removed (100/120, 150/180,  etc). I would not ask for filter type (FIR,IIR), design, ripple, Q factor, rolloff, etc.
