### ISSUE TITLE
Question 37 - Preprocessing Artifact Elimination Steps

### ISSUE THREAD

**Issue by ejmuraki** [INCF/artem-is#50]
The form creates tabs for each of the steps, which I missed because I was used to the display logic adding questions vertically (questions are shown below the previous one) and did not expect tabs. I think the tabs are cleaner, but maybe a note could be added to the info button for this question that let's people know that there will be a separate tab for each step?

**Comment by ufangYang** [comment]
either we provide a warming if people missed the table when they answer >2 or perhaps we reveal the questions vertically

**Comment by asoskic** [comment]
Thanks, good catch! Resolved now, the change will be visible when we updated the web-app :)
