### ISSUE TITLE
Design and sample: groups and logic flow

### ISSUE THREAD

**Issue by suzyjstyles** [INCF/artem-is#52]
•For Q4 and Q7 data check should exclude numeric entry for 0 groups and 0 conditions
Since this is not intuitive for all users we should add an info pop up for "If all participants not divided into separate groups, please enter 1 to indicate 1 condition " and "If your within subjects data is not divided into separate conditions, please enter 1 to indicate 1 condition" 

•If a user completes the participant number after exclusion (Q2) and 1 group (Q4) perhaps we can also autopopulate the N after exclusion per group? or skip the question as it is already complete. Perhaps the solution

•Q5 and Q8 (name of groups/conditions) can be hidden unless a value larger than 1 is input.

•Our group today expected for Q4 (between subjects) and Q7 (within subjects) to be more clearly linked - perhaps we can change the prompt text to make them more similar? suggestion:
How many participant groups/experimental conditions did the study have for between-subjects comparison? 
How many trial types/experimental conditions did the study have for within-subjects comparison?

•Q4 and Q7 mismatch in the structure of follow-on questions: 
Q4 How many participants did each **group** have after exclusion?
Missing alternative for comparison-wise exclusions (after Q7)

**Comment by asoskic** [comment]
Moved to other issues:
"If a user completes the participant number after exclusion (Q2) and 1 group (Q4) perhaps we can also autopopulate the N after exclusion per group? or skip the question as it is already complete. Perhaps the solution" -----> wishlist to add the autopopulating option (https://github.com/INCF/artem-is/issues/91)

"For Q4 and Q7 data check should exclude numeric entry for 0 groups and 0 conditions" ------> issue to add simple numerical limits (https://github.com/INCF/artem-is/issues/33)

**Comment by asoskic** [comment]
Resolved: "Since this is not intuitive for all users we should add an info pop up for "If all participants not divided into separate groups, please enter 1 to indicate 1 condition " and "If your within subjects data is not divided into separate conditions, please enter 1 to indicate 1 condition""

**Comment by asoskic** [comment]
Resolved: Q5 and Q8 (name of groups/conditions) can be hidden unless a value larger than 1 is input.

**Comment by asoskic** [comment]
Resolved  by putting them in the same sub-section called "Groups and within-subject conditions", this was indeed odd:
"•Our group today expected for Q4 (between subjects) and Q7 (within subjects) to be more clearly linked - perhaps we can change the prompt text to make them more similar? suggestion:
How many participant groups/experimental conditions did the study have for between-subjects comparison?
How many trial types/experimental conditions did the study have for within-subjects comparison?"

**Comment by asoskic** [comment]
**Remaining**:

"•Q4 and Q7 mismatch in the structure of follow-on questions:
Q4 How many participants did each group have after exclusion?
Missing alternative for comparison-wise exclusions (after Q7)"

This one is not clear: What would be the comparable question to "How many participants did each group have after exclusion?" for within-subject conditions?
If a participant is excluded, they are excluded from all conditions and this is visible in the question "How many participants, in total, were included in the analysis, after exclusion of participants?"
