### ISSUE TITLE
Epoching & Baseline correction: Q64, 67, 71, 72 can't input negative numbers using regular keyboard

### ISSUE THREAD

**Issue by suzyjstyles** [INCF/artem-is#57]
Instructions say: "For timings after the trigger, use positive numbers. For timings before the trigger, use negative numbers." but seem like validation in table is not quite matching

**Comment by suzyjstyles** [comment]
Just discovered that the 'minus' character works but not the hyphen that most keyboards have. Hopefully we can figure out a workaround for folks who don't know how to get the mathematical symbol efficiently (e.g., a button for minus?)

**Comment by asoskic** [comment]
Vanja and I checked with Dejan yesterday - inputting characters was blocked as a control of input, and a hyphen is a character, so it was a "collateral damage". For me, the minus button on the numerical keyboard didn't work either. We have asked @dpajicns to fix it :)
