### ISSUE TITLE
Stretch Goal: Order of operations

### ISSUE THREAD

**Issue by suzyjstyles** [INCF/artem-is#60]
Hope we can figure out a way to leverage the data input to facilitate completion of this section. Eg. a button to Auto-populate text answers from above questions (like in the PDF (in the default Q order), so a person can manually arrange into a list. As a stretch goal, could create a drag-and-drop interface where each named process can be dragged into a sequence.

**Comment by asoskic** [comment]
This is a duplicate - this bug is already open (https://github.com/INCF/artem-is/issues/2) :)
