### ISSUE TITLE
ERP-specific questions

### ISSUE THREAD

**Issue by suzyjstyles** [INCF/artem-is#61]
One of the outcomes of the SIPS workshop is that folks really like the layout and utility  of the apps early sections even if they're not doing ERP. Their suggestion is it would  be nice to ensure the template is modular, so separate sections can be used if useful, and additional  methods (like time/frequency domain analysis) could  have their own modular chunks tabs added later on. I'll make a list of sections that have ERP specific content, so we can think about how to make it more modular.

Study Description
Q13 (mentions epochs and ERPs as part of a list - not necessarily a problem, but could be good to make more general)

Pre-processing
Q61-67 Epoching
Q68-73 Baseline correction

Measurement 
Q1-74  All ERP-specific

Suggestion:
1. Shift Epoching and Baseline to Measurement? Or conditional questions for Epoching and Baselining, so they are hidden for people who aren't using those procedures? 
2. Rename Measurement to ERP Measurement, so a different module could be added/subbed in for different kinds of procedures?

**Comment by asoskic** [comment]
We had to make a decision before finalizing V1, and it made more sense to stick to the original plan because it doesn't endanger modularity longterm, as described above.
