### ISSUE TITLE
section titles

### ISSUE THREAD

**Issue by Mariella-Paul** [INCF/artem-is#62]
Hi all! I really like the little header icons for the different sections of the template! When I click on them, I also get the section title, but I would find it really useful to see the section titles right away (so all of them at once, next to their icons) so that it's easier to find the section I'm looking for right away

**Comment by asoskic** [comment]
Agreed, but this way it is better for the mobile version, and on desktop you can hover over the section logo :) In any case, one gets used to finding their way around sections fairly quickly :)
