### ISSUE TITLE
Selection of channels for analysis, average or individual

### ISSUE THREAD

**Issue by robertoostenveld** [INCF/artem-is#63]
The "Selection of channels for analysis" starts with 

> 1.Did you make a selection of channels for the purposes of statistical analysis?
>  - All channels were submitted to statistical analysis
>  - A subset of channels was submitted to statistical analysis

It is not clear to me how I would distinguish between doing  the analysis over all channels, or over an aggregate over channels. When selecting all channels, I could for example use https://pubmed.ncbi.nlm.nih.gov/2094301/. When selecting a subset of channels, I could keep the subset as is, but could also average the ERP over the channels.

**Comment by asoskic** [comment]
We were intially planning to leave aggregating channels into ROIs for the section on statistical analysis, but you are right, it fits better here. We added a few questions on this into the [cobidas_artemis table](https://docs.google.com/spreadsheets/d/1dlUt8_bHsM5mERFJkVLTVWanSlms6Ba8Wos38Dhmhfo/edit#gid=75463838), and they should become visible when Dejan updates the web-app.
