### ISSUE TITLE
When copying a template, the app should keep track of the ID of the "source" template

### ISSUE THREAD

**Issue by Remi-Gau** [INCF/artem-is#70]

**Comment by asoskic** [comment]
Only last source when it is a copy of a copy of a copy... If someone is really curious, they can go down the rabbit hole themselves, because it can be very long :D

**Comment by asoskic** [comment]
We have given up on this one after discussing it with Dejan. 

There are two main reasons:
1) There may be legitimate reasons for a person not to want to show source template, e.g. if they have a private template for their lab that they reuse, e.g. with hardware settings. They should be able not to show this if they want to, and they have other options such as Acknowledgements section to give credit when they do want to.
2) We cannot enforce showing source template when people can edit their JSON files and simply remove this part of the code if they really want to, so we should not take over the responsibility of ensuring that the source template is shown - giving credit should remain in the domain of the responsibility of the person doing a study as with any other kind of data researchers are handling.
