### ISSUE TITLE
Not possible to input negative numbers into float

### ISSUE THREAD

**Issue by asoskic** [INCF/artem-is#87]
We have items where users should be able to input negative values with decimals. They are currently float, but it does not allow inputting negative values. Which type should we put instead?

@Remi-Gau could you weigh in here too so that we are still in sync with other ecobidas tables :)

**Comment by Remi-Gau** [comment]
hum
I think "float" should include positive and negative values, so maybe this is on the validation side that something is wrong

**Comment by asoskic** [comment]
Vanja and I checked with Dejan today - inputting characters was blocked as a control of input, and a minus is a character, so it was a "collateral damage". 😅

**Comment by asoskic** [comment]
We have just seen that Suzy has opened this issue earlier. :)
