### ISSUE TITLE
Sign up on website fails

### ISSUE THREAD

**Issue by robertoostenveld** [INCF/artem-is#97]
I tried to sign up on https://artemis.incf.org/login 
I did not get an email confirmation. When I try to log in, I get "Email not found or incorrect password."

**Comment by Sulochan-khadka** [comment]
in fact there is another issue; when you click on sign in and then on register, they overlap. If you want me to solve this issue, assign me this issue.

**Comment by asoskic** [comment]
> 

Hi, Sulochan! Thank you for your offer. This project was on a several months break, and we are getting back to work these days, which is why we haven't seen your message until now. Are you still interested?

**Comment by Sulochan-khadka** [comment]
Yes and definitely yes...
I would be blessed to work on this project with you.

**Comment by Sulochan-khadka** [comment]
> > 
> 
> Hi, @Sulochan-khadka ! Thank you for your offer. This project was on a several months break, and we are getting back to work these days, which is why we haven't seen your message until now. Are you still interested?

Yes , for sure

**Comment by Sulochan-khadka** [comment]
I got another issue regarding the active button misbehaving... Should I publish an issue separately for this or solve including the previous...

**Comment by asoskic** [comment]
Hi! Thank you for your offer. Our team email is artemis.eeg.2020@gmail.com - please drop me a message so that we can connect, and perhaps it would be the easiest if we arranged a meeting

**Comment by asoskic** [comment]
Giorgio had this issue again recently (after it not appearing for a while), and it seems that Dejan resolved it. Fingers crossed it does not show up again, and I will close it for now. :)
